### ISSUE TITLE
README.md Url results in a 404 error page

### ISSUE THREAD

**Issue by berrak** [adafruit/Adafruit_ADXL343#13]
Hi,
The Url link on the second line in the README.md is (maybe) incorrect, or your server is down.
I did not expect to get a 404 error page as a result. However, I want to let you know the issue.
```
This driver is for the Adafruit ADXL343 Breakout (http://www.adafruit.com/products/) and is based on Adafruit's Unified Sensor Library (Adafruit_Sensor).
```
![AdafruitADXL343_404PageError](https://user-images.githubusercontent.com/1911497/182459531-7cf28d1c-16e5-4202-8d87-9567ac6edb92.png)

**Comment by evaherrada** [comment]
Fixed
